// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getPlaybackState: () => __TAURI_INVOKE<PlaybackSnapshot>("get_playback_state"),
	/**
	 *  Upcoming queue items from `offset` (at most `limit`), for the parts of a long queue the
	 *  snapshot does not carry.
	 */
	getPlaybackQueueWindow: (offset: number, limit: number) => __TAURI_INVOKE<PlaybackQueueWindow>("get_playback_queue_window", { offset, limit }),
	getPlaybackQueue: () => __TAURI_INVOKE<PlaybackQueueSnapshot>("get_playback_queue"),
	/**
	 *  Replaces the queue with `context` and plays from `start_track_id`, or from the context's
	 *  first track when it is `None`.
	 */
	startPlayback: (context: PlaybackContext, startTrackId: string | null) => __TAURI_INVOKE<PlaybackSnapshot>("start_playback", { context, startTrackId }),
	pausePlayback: () => __TAURI_INVOKE<PlaybackSnapshot>("pause_playback"),
	resumePlayback: () => __TAURI_INVOKE<PlaybackSnapshot>("resume_playback"),
	previousPlayback: () => __TAURI_INVOKE<PlaybackSnapshot>("previous_playback"),
	nextPlayback: () => __TAURI_INVOKE<PlaybackSnapshot>("next_playback"),
	seekPlayback: (positionMs: number) => __TAURI_INVOKE<PlaybackSnapshot>("seek_playback", { positionMs }),
	setPlaybackVolume: (volume: number) => __TAURI_INVOKE<PlaybackSnapshot>("set_playback_volume", { volume }),
	setPlaybackMuted: (muted: boolean) => __TAURI_INVOKE<PlaybackSnapshot>("set_playback_muted", { muted }),
	listAudioOutputDevices: () => __TAURI_INVOKE<AudioOutputDevice[]>("list_audio_output_devices"),
	setPlaybackRepeatMode: (mode: PlaybackRepeatMode) => __TAURI_INVOKE<PlaybackQueueSnapshot>("set_playback_repeat_mode", { mode }),
	setPlaybackShuffle: (enabled: boolean) => __TAURI_INVOKE<PlaybackQueueSnapshot>("set_playback_shuffle", { enabled }),
	/**  Switches the output device; a loaded track restarts on it at the same position. */
	setAudioOutputSelection: (selection: AudioOutputSelection) => __TAURI_INVOKE<PlaybackSnapshot>("set_audio_output_selection", { selection }),
	removeQueueItem: (id: string) => __TAURI_INVOKE<PlaybackQueueSnapshot>("remove_queue_item", { id }),
	moveQueueItem: (id: string, to: number) => __TAURI_INVOKE<PlaybackQueueSnapshot>("move_queue_item", { id, to }),
	/**  Makes an upcoming queue item current and plays it. */
	playQueueItem: (id: string) => __TAURI_INVOKE<PlaybackSnapshot>("play_queue_item", { id }),
	/**
	 *  Adds a library track to the queue: right after the current one (`next`) or at the end.
	 *  With nothing queued it starts playing.
	 */
	enqueueTrack: (trackId: string, next: boolean) => __TAURI_INVOKE<PlaybackQueueSnapshot>("enqueue_track", { trackId, next }),
	clearQueue: () => __TAURI_INVOKE<PlaybackQueueSnapshot>("clear_queue"),
	/**  Waveform of the loaded track, or `None` while it is analyzed; `waveformReady` follows. */
	getPlaybackWaveform: (path: string) => __TAURI_INVOKE<{
	path: string,
	peaks: number[],
	rms: number[],
} | null>("get_playback_waveform", { path }),
	getLibraryStatus: () => __TAURI_INVOKE<LibraryStatus>("get_library_status"),
	getLibraryScanState: () => __TAURI_INVOKE<LibraryScanSnapshot>("get_library_scan_state"),
	listLibraryRoots: () => __TAURI_INVOKE<LibraryRoot[]>("list_library_roots"),
	registerLibraryRoot: (path: string) => __TAURI_INVOKE<LibraryRoot>("register_library_root", { path }),
	setLibraryRootEnabled: (id: string, enabled: boolean) => __TAURI_INVOKE<LibraryRoot>("set_library_root_enabled", { id, enabled }),
	removeLibraryRoot: (id: string) => __TAURI_INVOKE<null>("remove_library_root", { id }),
	startLibraryScan: () => __TAURI_INVOKE<null>("start_library_scan"),
	cancelLibraryScan: () => __TAURI_INVOKE<null>("cancel_library_scan"),
	listLibraryTracks: (cursor: string | null, search: string | null, sortKey: LibraryTrackSortKey, sortDirection: LibrarySortDirection) => __TAURI_INVOKE<LibraryTrackPage>("list_library_tracks", { cursor, search, sortKey, sortDirection }),
	listLibraryAlbums: (cursor: string | null, search: string | null, sortKey: LibraryAlbumSortKey, sortDirection: LibrarySortDirection) => __TAURI_INVOKE<LibraryAlbumPage>("list_library_albums", { cursor, search, sortKey, sortDirection }),
	listLibraryAlbumArtists: (cursor: string | null, search: string | null, sortKey: LibraryAlbumArtistSortKey, sortDirection: LibrarySortDirection) => __TAURI_INVOKE<LibraryAlbumArtistPage>("list_library_album_artists", { cursor, search, sortKey, sortDirection }),
	getLibraryAlbumArtist: (artistKey: LibraryAlbumArtistKey) => __TAURI_INVOKE<LibraryAlbumArtistSummary>("get_library_album_artist", { artistKey }),
	listLibraryArtistAlbums: (artistKey: LibraryAlbumArtistKey, cursor: string | null, sortKey: LibraryArtistAlbumSortKey, sortDirection: LibrarySortDirection) => __TAURI_INVOKE<LibraryAlbumPage>("list_library_artist_albums", { artistKey, cursor, sortKey, sortDirection }),
	getLibraryAlbumDetails: (albumKey: LibraryAlbumKey) => __TAURI_INVOKE<LibraryAlbumDetails>("get_library_album_details", { albumKey }),
	listLibraryAlbumTracks: (albumKey: LibraryAlbumKey, cursor: string | null) => __TAURI_INVOKE<LibraryAlbumTrackPage>("list_library_album_tracks", { albumKey, cursor }),
	getLibraryTrack: (trackId: string) => __TAURI_INVOKE<{
	id: string,
	title: string,
	artist: string | null,
	album: string | null,
	albumArtist: string | null,
	/**  The key the catalog files the track's album under, `None` for a track with no album tag. */
	albumKey: LibraryAlbumKey | null,
	artwork: ArtworkRef | null,
	durationMs: number | null,
	fileFormat: string | null,
	bitDepth: number | null,
	bitrateKbps: number | null,
	availability: LibraryFileAvailability,
	playable: boolean,
} | null>("get_library_track", { trackId }),
	getLibraryTrackProperties: (trackId: string) => __TAURI_INVOKE<{
	id: string,
	path: string,
	fileName: string,
	title: string | null,
	artist: string | null,
	album: string | null,
	albumArtist: string | null,
	trackNumber: number | null,
	trackTotal: number | null,
	discNumber: number | null,
	discTotal: number | null,
	genre: string | null,
	date: string | null,
	durationMs: number | null,
	fileFormat: string | null,
	codec: string | null,
	sampleRate: number | null,
	channelCount: number | null,
	bitDepth: number | null,
	bitrateKbps: number | null,
} | null>("get_library_track_properties", { trackId }),
	/**  Shows the track's file in Explorer, selected. */
	revealLibraryTrack: (trackId: string) => __TAURI_INVOKE<null>("reveal_library_track", { trackId }),
	getArtworkAccent: (contentHash: string) => __TAURI_INVOKE<string | null>("get_artwork_accent", { contentHash }),
	getTrackLyrics: (trackId: string) => __TAURI_INVOKE<LyricsResolution>("get_track_lyrics", { trackId }),
	getSettings: () => __TAURI_INVOKE<AppearanceSettings>("get_settings"),
	/**  Applies a partial update and returns the appearance settings as they are afterwards. */
	updateSettings: (patch: SettingsPatch) => __TAURI_INVOKE<AppearanceSettings>("update_settings", { patch }),
};

/* Types */
/**  A loaded track: identity plus how it reaches the output device. */
export type ActiveSession = {
	item: PlaybackItem,
	playbackId: string,
	positionMs: number,
	/**
	 *  Counts the seeks the player has completed. A change means the position jumped on
	 *  purpose, so a display can react to the jump instead of guessing it from the numbers.
	 */
	seekRevision: number,
	durationMs: number | null,
	outputDevice: AudioOutputDeviceIdentity,
	channelConversion: PlaybackChannelConversion,
	/**
	 *  The loaded file's format (its extension when the library has none), bit depth and
	 *  average bitrate: the start of the signal path.
	 */
	sourceFormat: string,
	sourceBitDepth: number | null,
	sourceBitrateKbps: number | null,
	sourceSampleRate: number,
	outputSampleRate: number,
	resamplingActive: boolean,
};

export type AppEvent = { event: "playbackStateChanged"; payload: PlaybackSnapshot } | { event: "playbackQueueStateChanged"; payload: PlaybackQueueSnapshot } | { event: "applicationActivitiesChanged"; payload: ApplicationActivity[] } | { event: "libraryScanStateChanged"; payload: LibraryScanSnapshot } | { event: "waveformReady"; payload: {
	path: string,
} } | { event: "settingsChanged"; payload: AppearanceSettings };

export type AppearancePatch = {
	artworkBackdrop: boolean | null,
	calmMotion: boolean | null,
};

/**
 *  What the renderer reads and writes. Every field is always present, so the renderer declares
 *  no defaults of its own; a saved file missing a field takes the default here.
 */
export type AppearanceSettings = {
	/**  Artwork light behind the library and Now Playing. */
	artworkBackdrop: boolean,
	/**  Only what marks the position moves by itself: nothing breathes or lifts on its own. */
	calmMotion: boolean,
};

export type ApplicationActivity = {
	id: string,
	kind: ApplicationActivityKind,
	state: ApplicationActivityState,
};

export type ApplicationActivityKind = "librarySync";

export type ApplicationActivityState = "running" | "attentionRequired";

export type ArtworkMimeType = "jpeg" | "png";

/**  Stored artwork as the renderer addresses it. Shared by the library catalog and playback items. */
export type ArtworkRef = {
	contentHash: string,
	mimeType: ArtworkMimeType,
	relativePath: string,
};

export type AudioDeviceListError = { code: "enumerationFailed" };

export type AudioOutputDevice = {
	id: string,
	name: string,
	isDefault: boolean,
};

export type AudioOutputDeviceIdentity = {
	id: string,
	name: string,
};

export type AudioOutputSelection = { kind: "systemDefault" } | { kind: "device"; deviceId: string };

export type LibraryAlbumArtistKey = {
	name: string,
};

export type LibraryAlbumArtistPage = {
	items: LibraryAlbumArtistSummary[],
	totalCount: number,
	nextCursor: string | null,
};

export type LibraryAlbumArtistSortKey = "artist" | "albumCount" | "trackCount";

export type LibraryAlbumArtistSummary = {
	key: LibraryAlbumArtistKey,
	artwork: ArtworkRef | null,
	albumCount: number,
	trackCount: number,
};

export type LibraryAlbumDetails = {
	summary: LibraryAlbumSummary,
	date: string | null,
	trackCount: number,
	durationMs: number | null,
	firstPlayableTrackId: string | null,
};

export type LibraryAlbumKey = {
	title: string,
	albumArtist: string,
};

export type LibraryAlbumPage = {
	items: LibraryAlbumSummary[],
	totalCount: number,
	nextCursor: string | null,
};

export type LibraryAlbumSortKey = "title" | "artist" | "year";

export type LibraryAlbumSummary = {
	key: LibraryAlbumKey,
	artwork: ArtworkRef | null,
	year: number | null,
};

export type LibraryAlbumTrackPage = {
	items: LibraryAlbumTrackSummary[],
	totalCount: number,
	nextCursor: string | null,
};

export type LibraryAlbumTrackSummary = {
	id: string,
	title: string,
	artist: string | null,
	trackNumber: number | null,
	discNumber: number | null,
	fileFormat: string | null,
	bitDepth: number | null,
	sampleRate: number | null,
	durationMs: number | null,
	availability: LibraryFileAvailability,
	playable: boolean,
};

export type LibraryArtistAlbumSortKey = "year" | "title";

export type LibraryCommandError = { code: "invalidRoot" } | { code: "rootNotDirectory" } | { code: "canonicalizationFailed" } | { code: "duplicateRoot" } | { code: "overlappingRoot" } | { code: "scanInProgress" } | { code: "invalidId" } | { code: "trackNotFound" } | { code: "trackUnavailable" } | { code: "albumNotFound" } | { code: "invalidCursor" } | { code: "invalidAlbumKey" } | { code: "invalidAlbumArtistKey" } | { code: "albumArtistNotFound" } | { code: "rootMissing" } | { code: "scanAlreadyRunning" } | { code: "noEnabledRoots" } | { code: "scanNotRunning" } | { code: "libraryUnavailable" } | { code: "persistenceFailed" } | { code: "taskFailed" };

export type LibraryFileAvailability = "available" | "missing";

export type LibraryRoot = {
	id: string,
	path: string,
	enabled: boolean,
	scanGeneration: number,
	lastSuccessfulScanAtMs: number | null,
};

export type LibraryScanSnapshot = {
	state: LibraryScanState,
	currentRoot: LibraryRoot | null,
	/**
	 *  How many files the previous scans left in the scanned folders: what a rescan can expect
	 *  to find, so its progress can be shown as a share. 0 when there is no such history.
	 */
	expectedCount: number,
	discoveredCount: number,
	inspectedCount: number,
	indexedCount: number,
	failedCount: number,
	failureCode: ScanFailure | null,
};

export type LibraryScanState = "idle" | "running" | "completed" | "cancelled" | "failed";

export type LibrarySortDirection = "ascending" | "descending";

export type LibraryStatus = { status: "ready" } | { status: "unavailable"; reason: LibraryUnavailableReason };

export type LibraryTrackPage = {
	items: LibraryTrackSummary[],
	totalCount: number,
	nextCursor: string | null,
};

/**  The tags, audio format and location of one track, as the Properties view lists them. */
export type LibraryTrackProperties = {
	id: string,
	path: string,
	fileName: string,
	title: string | null,
	artist: string | null,
	album: string | null,
	albumArtist: string | null,
	trackNumber: number | null,
	trackTotal: number | null,
	discNumber: number | null,
	discTotal: number | null,
	genre: string | null,
	date: string | null,
	durationMs: number | null,
	fileFormat: string | null,
	codec: string | null,
	sampleRate: number | null,
	channelCount: number | null,
	bitDepth: number | null,
	bitrateKbps: number | null,
};

export type LibraryTrackSortKey = "title" | "artist" | "album" | "duration";

export type LibraryTrackSummary = {
	id: string,
	title: string,
	artist: string | null,
	album: string | null,
	albumArtist: string | null,
	/**  The key the catalog files the track's album under, `None` for a track with no album tag. */
	albumKey: LibraryAlbumKey | null,
	artwork: ArtworkRef | null,
	durationMs: number | null,
	fileFormat: string | null,
	bitDepth: number | null,
	bitrateKbps: number | null,
	availability: LibraryFileAvailability,
	playable: boolean,
};

export type LibraryUnavailableReason = "databaseOpenFailed" | "migrationFailed" | "schemaTooNew" | "databaseCorrupt";

export type LyricsCommandError = { code: "invalidId" } | { code: "trackNotFound" } | { code: "trackUnavailable" } | { code: "libraryUnavailable" } | { code: "persistenceFailed" } | { code: "taskFailed" };

export type LyricsContent = { kind: "plain"; lines: string[] } | { kind: "timed"; lines: LyricsTimedLine[] };

export type LyricsDocument = {
	source: LyricsSourceKind,
	language: string | null,
	content: LyricsContent,
};

export type LyricsResolution = { status: "resolved"; trackId: string; document: LyricsDocument; notice: LyricsResolutionNotice | null } | { status: "notFound"; trackId: string } | { status: "sourceFailed"; trackId: string };

export type LyricsResolutionNotice = "sidecarFailedUsingEmbedded";

export type LyricsSourceKind = "sidecar" | "embedded";

export type LyricsTimedLine = {
	startMs: number,
	text: string,
};

export type PlaybackChannelConversion = "none" | "monoToStereo" | "stereoToMono" | "downmix";

export type PlaybackContext = 
/**  An album in disc and track order. */
{ kind: "album"; key: LibraryAlbumKey } | 
/**  Exactly these library tracks in this order: how a replaced queue is put back. */
{ kind: "trackIds"; trackIds: string[] } | 
/**  The tracks list as currently filtered and sorted. */
{ kind: "tracks"; search: string | null; sortKey: LibraryTrackSortKey; sortDirection: LibrarySortDirection };

export type PlaybackFailureCode = "noOutputDevice" | "outputDeviceUnavailable" | "unsupportedOutputConfiguration" | "outputStreamBuildFailed" | "outputStreamStartFailed" | "outputStreamPauseFailed" | "outputStreamResumeFailed" | "outputStreamRuntimeFailed" | "completionTimingFailed" | "decodeFailed" | "sampleRateConversionFailed";

/**
 *  One entry of the playback queue and the identity of the loaded track.
 * 
 *  Everything a listener-facing feature needs about "what is playing" lives here, so history,
 *  system media controls, and the UI never have to look the track up again by path.
 */
export type PlaybackItem = {
	queueItemId: string,
	trackId: string | null,
	file: ValidatedAudioFile,
	title: string,
	artist: string | null,
	album: string | null,
	albumArtist: string | null,
	artwork: ArtworkRef | null,
	durationMs: number | null,
	/**  From the library's metadata; `None` for a file outside it. */
	trackNumber: number | null,
	discNumber: number | null,
	year: number | null,
	/**  The catalog key of the album, for links; `None` when the file has no album. */
	albumKey: LibraryAlbumKey | null,
	/**  Tracks the library holds for the album. */
	albumTrackCount: number | null,
};

/**  A queue entry as the queue panel shows it; the file path stays in the backend. */
export type PlaybackQueueItem = {
	id: string,
	trackId: string | null,
	title: string,
	artist: string | null,
	album: string | null,
	artwork: ArtworkRef | null,
	durationMs: number | null,
};

/**
 *  The queue as the renderer mirrors it: the current item, the last few played, the first
 *  upcoming ones, and how many there are in all. Longer queues are read with `window`, so a
 *  library-sized queue never crosses the IPC boundary in one piece.
 */
export type PlaybackQueueSnapshot = {
	revision: number,
	current: PlaybackQueueItem | null,
	/**  The most recently played items, oldest first. */
	history: PlaybackQueueItem[],
	historyCount: number,
	upcoming: PlaybackQueueItem[],
	upcomingCount: number,
	repeatMode: PlaybackRepeatMode,
	shuffleEnabled: boolean,
};

/**  A slice of the upcoming list, tagged with the queue revision it was cut from. */
export type PlaybackQueueWindow = {
	revision: number,
	offset: number,
	items: PlaybackQueueItem[],
};

export type PlaybackRepeatMode = "off" | "all" | "one";

/**
 *  Why a playback request failed: the one error vocabulary for every command that plays or
 *  queues, serialized as `{ "code": "<camelCase>" }`.
 */
export type PlaybackServiceError = { code: "invalidArgument" } | { code: "workerUnavailable" } | 
/**  A newer request replaced this one before it finished; the caller should not report it. */
{ code: "superseded" } | { code: "queueItemNotFound" } | { code: "queueBusy" } | { code: "invalidVolume" } | { code: "invalidDeviceId" } | { code: "invalidPlaybackState" } | { code: "durationUnavailable" } | { code: "seekFailed" } | { code: "decodeFailed" } | { code: "noOutputDevice" } | { code: "outputDeviceUnavailable" } | { code: "unsupportedOutputConfiguration" } | { code: "outputStreamBuildFailed" } | { code: "outputStreamStartFailed" } | { code: "outputStreamPauseFailed" } | { code: "outputStreamResumeFailed" } | { code: "outputStreamRuntimeFailed" } | { code: "completionTimingFailed" } | { code: "sampleRateConversionFailed" } | { code: "invalidAlbumKey" } | { code: "invalidTrackId" } | { code: "albumNotFound" } | { code: "trackNotMember" } | { code: "trackUnavailable" } | { code: "trackNotPlayable" } | { code: "noPlayableTracks" } | { code: "libraryUnavailable" } | { code: "persistenceFailed" } | { code: "taskFailed" };

export type PlaybackSnapshot = 
/**  `item` is the last track that played, kept so the UI can still say what it was. */
{ status: "stopped"; base: SnapshotBase; item: PlaybackItem | null } | { status: "playing"; base: SnapshotBase; session: ActiveSession } | { status: "paused"; base: SnapshotBase; session: ActiveSession } | { status: "failed"; base: SnapshotBase; item: PlaybackItem | null; playbackId: string | null; error: PlaybackFailureCode };

export type PlaybackWaveform = {
	path: string,
	peaks: number[],
	rms: number[],
};

/**  Why a scan stopped without finishing. */
export type ScanFailure = "persistenceFailed" | "rootTraversalFailed";

/**
 *  A partial update from the renderer; absent fields stay as they are. Playback preferences are
 *  not here: the playback worker owns them and records every change itself.
 */
export type SettingsPatch = {
	appearance: AppearancePatch | null,
};

/**  Fields every transport state carries. */
export type SnapshotBase = {
	revision: number,
	volume: number,
	muted: boolean,
	outputSelection: AudioOutputSelection,
	canGoPrevious: boolean,
	canGoNext: boolean,
};

export type ValidatedAudioFile = {
	path: string,
	fileName: string,
	extension: string,
};

