// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getPlaybackState: () => __TAURI_INVOKE<PlaybackSnapshot>("get_playback_state"),
	getPlaybackQueue: () => __TAURI_INVOKE<PlaybackQueueSnapshot>("get_playback_queue"),
	pausePlayback: () => __TAURI_INVOKE<PlaybackSnapshot>("pause_playback"),
	resumePlayback: () => __TAURI_INVOKE<PlaybackSnapshot>("resume_playback"),
	previousPlayback: () => __TAURI_INVOKE<PlaybackSnapshot>("previous_playback"),
	nextPlayback: () => __TAURI_INVOKE<PlaybackSnapshot>("next_playback"),
	seekPlayback: (positionMs: number) => __TAURI_INVOKE<PlaybackSnapshot>("seek_playback", { positionMs }),
	setPlaybackVolume: (volume: number) => __TAURI_INVOKE<PlaybackSnapshot>("set_playback_volume", { volume }),
	setPlaybackMuted: (muted: boolean) => __TAURI_INVOKE<PlaybackSnapshot>("set_playback_muted", { muted }),
	listAudioOutputDevices: () => __TAURI_INVOKE<AudioOutputDevice[]>("list_audio_output_devices"),
	getLibraryStatus: () => __TAURI_INVOKE<LibraryStatus>("get_library_status"),
	getLibraryScanState: () => __TAURI_INVOKE<LibraryScanSnapshot>("get_library_scan_state"),
	listLibraryRoots: () => __TAURI_INVOKE<LibraryRoot[]>("list_library_roots"),
	registerLibraryRoot: (path: string) => __TAURI_INVOKE<LibraryRoot>("register_library_root", { path }),
	setLibraryRootEnabled: (id: string, enabled: boolean) => __TAURI_INVOKE<LibraryRoot>("set_library_root_enabled", { id, enabled }),
	removeLibraryRoot: (id: string) => __TAURI_INVOKE<null>("remove_library_root", { id }),
	startLibraryScan: () => __TAURI_INVOKE<null>("start_library_scan"),
	cancelLibraryScan: () => __TAURI_INVOKE<null>("cancel_library_scan"),
	listLibraryTracks: (cursor: string | null, search: string | null, sortKey: LibraryTrackSortKey, sortDirection: LibrarySortDirection) => __TAURI_INVOKE<LibraryTrackPage>("list_library_tracks", { cursor, search, sortKey, sortDirection }),
	listLibraryAlbums: (cursor: string | null, search: string | null, sortKey: LibraryAlbumSortKey, sortDirection: LibrarySortDirection) => __TAURI_INVOKE<LibraryAlbumPage>("list_library_albums", { cursor, search, sortKey, sortDirection }),
	listLibraryAlbumArtists: (cursor: string | null, search: string | null, sortKey: LibraryAlbumArtistSortKey, sortDirection: LibrarySortDirection) => __TAURI_INVOKE<LibraryAlbumArtistPage>("list_library_album_artists", { cursor, search, sortKey, sortDirection }),
	getLibraryAlbumArtist: (artistKey: LibraryAlbumArtistKey) => __TAURI_INVOKE<LibraryAlbumArtistSummary>("get_library_album_artist", { artistKey }),
	listLibraryArtistAlbums: (artistKey: LibraryAlbumArtistKey, cursor: string | null, sortKey: LibraryArtistAlbumSortKey, sortDirection: LibrarySortDirection) => __TAURI_INVOKE<LibraryAlbumPage>("list_library_artist_albums", { artistKey, cursor, sortKey, sortDirection }),
	getLibraryAlbumDetails: (albumKey: LibraryAlbumKey) => __TAURI_INVOKE<LibraryAlbumDetails>("get_library_album_details", { albumKey }),
	listLibraryAlbumTracks: (albumKey: LibraryAlbumKey, cursor: string | null) => __TAURI_INVOKE<LibraryAlbumTrackPage>("list_library_album_tracks", { albumKey, cursor }),
	getLibraryTrackForPath: (path: string) => __TAURI_INVOKE<{
	id: string,
	title: string,
	artist: string | null,
	album: string | null,
	albumArtist: string | null,
	artwork: ArtworkRef | null,
	durationMs: number | null,
	availability: LibraryFileAvailability,
	playable: boolean,
} | null>("get_library_track_for_path", { path }),
	startLibraryTrack: (trackId: string) => __TAURI_INVOKE<PlaybackSnapshot>("start_library_track", { trackId }),
	startLibraryAlbum: (albumKey: LibraryAlbumKey) => __TAURI_INVOKE<PlaybackSnapshot>("start_library_album", { albumKey }),
};

/* Types */
export type AppEvent = { event: "playbackStateChanged"; payload: PlaybackSnapshot } | { event: "playbackQueueStateChanged"; payload: PlaybackQueueSnapshot } | { event: "applicationActivitiesChanged"; payload: ApplicationActivity[] } | { event: "libraryScanStateChanged"; payload: LibraryScanSnapshot };

export type ApplicationActivity = {
	id: string,
	kind: ApplicationActivityKind,
	state: ApplicationActivityState,
};

export type ApplicationActivityKind = "librarySync";

export type ApplicationActivityState = "running" | "attentionRequired";

export type ArtworkMimeType = "jpeg" | "png";

export type ArtworkRef = {
	contentHash: string,
	mimeType: ArtworkMimeType,
	relativePath: string,
};

export type AudioDeviceListError = { code: "enumerationFailed" };

export type AudioOutputDevice = {
	id: string,
	name: string,
	isDefault: boolean,
};

export type AudioOutputDeviceIdentity = {
	id: string,
	name: string,
};

export type AudioOutputSelection = { kind: "systemDefault" } | { kind: "device"; deviceId: string };

export type LibraryAlbumArtistKey = {
	name: string,
};

export type LibraryAlbumArtistPage = {
	items: LibraryAlbumArtistSummary[],
	totalCount: number,
	nextCursor: string | null,
};

export type LibraryAlbumArtistSortKey = "artist" | "albumCount" | "trackCount";

export type LibraryAlbumArtistSummary = {
	key: LibraryAlbumArtistKey,
	artwork: ArtworkRef | null,
	albumCount: number,
	trackCount: number,
};

export type LibraryAlbumDetails = {
	summary: LibraryAlbumSummary,
	date: string | null,
	trackCount: number,
	durationMs: number | null,
	firstPlayableTrackId: string | null,
};

export type LibraryAlbumKey = {
	title: string,
	albumArtist: string,
};

export type LibraryAlbumPage = {
	items: LibraryAlbumSummary[],
	totalCount: number,
	nextCursor: string | null,
};

export type LibraryAlbumSortKey = "title" | "artist" | "year";

export type LibraryAlbumSummary = {
	key: LibraryAlbumKey,
	artwork: ArtworkRef | null,
	year: number | null,
};

export type LibraryAlbumTrackPage = {
	items: LibraryAlbumTrackSummary[],
	totalCount: number,
	nextCursor: string | null,
};

export type LibraryAlbumTrackSummary = {
	id: string,
	title: string,
	artist: string | null,
	trackNumber: number | null,
	discNumber: number | null,
	fileFormat: string | null,
	bitDepth: number | null,
	sampleRate: number | null,
	durationMs: number | null,
	availability: LibraryFileAvailability,
	playable: boolean,
};

export type LibraryArtistAlbumSortKey = "year" | "title";

export type LibraryCommandError = { code: "invalidRoot" } | { code: "rootNotFound" } | { code: "rootNotDirectory" } | { code: "canonicalizationFailed" } | { code: "duplicateRoot" } | { code: "overlappingRoot" } | { code: "scanInProgress" } | { code: "invalidId" } | { code: "albumNotFound" } | { code: "invalidCursor" } | { code: "invalidAlbumKey" } | { code: "invalidAlbumArtistKey" } | { code: "albumArtistNotFound" } | { code: "rootMissing" } | { code: "scanAlreadyRunning" } | { code: "noEnabledRoots" } | { code: "scanNotRunning" } | { code: "libraryUnavailable" } | { code: "persistenceFailed" } | { code: "taskFailed" };

export type LibraryFileAvailability = "available" | "missing";

export type LibraryRoot = {
	id: string,
	path: string,
	enabled: boolean,
	scanGeneration: number,
	lastSuccessfulScanAtMs: number | null,
};

export type LibraryScanSnapshot = {
	state: LibraryScanState,
	currentRoot: LibraryRoot | null,
	discoveredCount: number,
	inspectedCount: number,
	indexedCount: number,
	failedCount: number,
	failureCode: string | null,
};

export type LibraryScanState = "idle" | "running" | "completed" | "cancelled" | "failed";

export type LibrarySortDirection = "ascending" | "descending";

export type LibraryStatus = { status: "ready" } | { status: "unavailable"; reason: LibraryUnavailableReason };

export type LibraryTrackPage = {
	items: LibraryTrackSummary[],
	totalCount: number,
	nextCursor: string | null,
};

export type LibraryTrackSortKey = "title" | "artist" | "album" | "duration";

export type LibraryTrackSummary = {
	id: string,
	title: string,
	artist: string | null,
	album: string | null,
	albumArtist: string | null,
	artwork: ArtworkRef | null,
	durationMs: number | null,
	availability: LibraryFileAvailability,
	playable: boolean,
};

export type LibraryUnavailableReason = "storageUnavailable" | "databaseOpenFailed" | "migrationFailed" | "schemaTooNew" | "databaseCorrupt";

export type PlaybackChannelConversion = "none" | "monoToStereo" | "stereoToMono";

/**  Structured playback command failure serialized as `{ "code": "<camelCase>" }`. */
export type PlaybackCommandError = { code: "invalidArgument" } | { code: "playbackWorkerUnavailable" } | { code: "queueItemNotFound" } | { code: "queueBusy" } | { code: "invalidVolume" } | { code: "invalidDeviceId" } | { code: "invalidPlaybackState" } | { code: "durationUnavailable" } | { code: "seekFailed" } | { code: "decodeFailed" } | { code: "noOutputDevice" } | { code: "outputDeviceUnavailable" } | { code: "unsupportedOutputConfiguration" } | { code: "outputStreamBuildFailed" } | { code: "outputStreamStartFailed" } | { code: "outputStreamPauseFailed" } | { code: "outputStreamResumeFailed" } | { code: "outputStreamRuntimeFailed" } | { code: "completionTimingFailed" } | { code: "sampleRateConversionFailed" };

export type PlaybackFailureCode = "noOutputDevice" | "outputDeviceUnavailable" | "unsupportedOutputConfiguration" | "outputStreamBuildFailed" | "outputStreamStartFailed" | "outputStreamPauseFailed" | "outputStreamResumeFailed" | "outputStreamRuntimeFailed" | "completionTimingFailed" | "decodeFailed" | "sampleRateConversionFailed";

export type PlaybackQueueItem = {
	id: string,
	title: string,
	artist: string | null,
	durationMs: number | null,
};

export type PlaybackQueueSnapshot = {
	revision: number,
	current: PlaybackQueueItem | null,
	upcoming: PlaybackQueueItem[],
	repeatMode: PlaybackRepeatMode,
	shuffleEnabled: boolean,
};

export type PlaybackRepeatMode = "off" | "all" | "one";

export type PlaybackSnapshot = { status: "stopped"; revision: number; file: ValidatedAudioFile | null; volume: number; muted: boolean; outputSelection: AudioOutputSelection; canGoPrevious: boolean; canGoNext: boolean } | { status: "playing"; revision: number; file: ValidatedAudioFile; playbackId: string; positionMs: number; durationMs: number | null; volume: number; muted: boolean; outputSelection: AudioOutputSelection; outputDevice: AudioOutputDeviceIdentity; channelConversion: PlaybackChannelConversion; sourceSampleRate: number; outputSampleRate: number; resamplingActive: boolean; canGoPrevious: boolean; canGoNext: boolean } | { status: "paused"; revision: number; file: ValidatedAudioFile; playbackId: string; positionMs: number; durationMs: number | null; volume: number; muted: boolean; outputSelection: AudioOutputSelection; outputDevice: AudioOutputDeviceIdentity; channelConversion: PlaybackChannelConversion; sourceSampleRate: number; outputSampleRate: number; resamplingActive: boolean; canGoPrevious: boolean; canGoNext: boolean } | { status: "failed"; revision: number; file: ValidatedAudioFile | null; playbackId: string | null; error: PlaybackFailureCode; volume: number; muted: boolean; outputSelection: AudioOutputSelection; canGoPrevious: boolean; canGoNext: boolean };

export type StartLibraryAlbumTrackError = { code: "invalidAlbumKey" } | { code: "invalidTrackId" } | { code: "albumNotFound" } | { code: "trackNotMember" } | { code: "trackUnavailable" } | { code: "trackNotPlayable" } | { code: "noPlayableTracks" } | { code: "sourceUnavailable" } | { code: "libraryUnavailable" } | { code: "persistenceFailed" } | { code: "decodeFailed" } | { code: "noOutputDevice" } | { code: "outputDeviceUnavailable" } | { code: "outputFailed" } | { code: "playbackWorkerUnavailable" } | { code: "taskFailed" };

export type StartLibraryTrackError = { code: "invalidId" } | { code: "trackNotFound" } | { code: "trackUnavailable" } | { code: "trackNotPlayable" } | { code: "libraryUnavailable" } | { code: "persistenceFailed" } | { code: "decodeFailed" } | { code: "noOutputDevice" } | { code: "outputDeviceUnavailable" } | { code: "outputFailed" } | { code: "playbackWorkerUnavailable" } | { code: "taskFailed" };

export type ValidatedAudioFile = {
	path: string,
	fileName: string,
	extension: string,
};

