export const IPC_CHANNELS = {
  playback: {
    getState: "playback:get-state",
    getQueue: "playback:get-queue",
    pause: "playback:pause",
    resume: "playback:resume",
    previous: "playback:previous",
    next: "playback:next",
    seek: "playback:seek",
    setVolume: "playback:set-volume",
    setMuted: "playback:set-muted",
    startTrack: "library:start-track",
    startAlbum: "library:start-album",
  },
  library: {
    status: "library:get-status",
    roots: "library:list-roots",
    registerRoot: "library:register-root",
    setRootEnabled: "library:set-root-enabled",
    removeRoot: "library:remove-root",
    scan: "library:get-scan-state",
    startScan: "library:start-scan",
    cancelScan: "library:cancel-scan",
    listTracks: "library:list-tracks",
    listAlbums: "library:list-albums",
    listAlbumArtists: "library:list-album-artists",
    getAlbumArtist: "library:get-album-artist",
    listArtistAlbums: "library:list-artist-albums",
    getAlbumDetails: "library:get-album-details",
    listAlbumTracks: "library:list-album-tracks",
    getTrackForPath: "library:get-track-for-path",
  },
  platform: { selectLibraryDirectory: "platform:select-library-directory" },
} as const;
