/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryTracksRouteImport } from './routes/library.tracks'
import { Route as LibraryAlbumArtistsIndexRouteImport } from './routes/library.album-artists.index'
import { Route as LibraryAlbumArtistsArtistNameRouteImport } from './routes/library.album-artists.$artistName'
import { Route as LibraryAlbumsIndexRouteImport } from './routes/library.albums.index'
import { Route as LibraryAlbumsAlbumArtistAlbumTitleRouteImport } from './routes/library.albums.$albumArtist.$albumTitle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryTracksRoute = LibraryTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryAlbumArtistsIndexRoute =
  LibraryAlbumArtistsIndexRouteImport.update({
    id: '/album-artists/',
    path: '/album-artists/',
    getParentRoute: () => LibraryRoute,
  } as any)
const LibraryAlbumArtistsArtistNameRoute =
  LibraryAlbumArtistsArtistNameRouteImport.update({
    id: '/album-artists/$artistName',
    path: '/album-artists/$artistName',
    getParentRoute: () => LibraryRoute,
  } as any)
const LibraryAlbumsIndexRoute = LibraryAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryAlbumsAlbumArtistAlbumTitleRoute =
  LibraryAlbumsAlbumArtistAlbumTitleRouteImport.update({
    id: '/albums/$albumArtist/$albumTitle',
    path: '/albums/$albumArtist/$albumTitle',
    getParentRoute: () => LibraryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/library/tracks': typeof LibraryTracksRoute
  '/library/': typeof LibraryIndexRoute
  '/library/album-artists/$artistName': typeof LibraryAlbumArtistsArtistNameRoute
  '/library/album-artists/': typeof LibraryAlbumArtistsIndexRoute
  '/library/albums/': typeof LibraryAlbumsIndexRoute
  '/library/albums/$albumArtist/$albumTitle': typeof LibraryAlbumsAlbumArtistAlbumTitleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/library/tracks': typeof LibraryTracksRoute
  '/library': typeof LibraryIndexRoute
  '/library/album-artists/$artistName': typeof LibraryAlbumArtistsArtistNameRoute
  '/library/album-artists': typeof LibraryAlbumArtistsIndexRoute
  '/library/albums': typeof LibraryAlbumsIndexRoute
  '/library/albums/$albumArtist/$albumTitle': typeof LibraryAlbumsAlbumArtistAlbumTitleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/library/tracks': typeof LibraryTracksRoute
  '/library/': typeof LibraryIndexRoute
  '/library/album-artists/$artistName': typeof LibraryAlbumArtistsArtistNameRoute
  '/library/album-artists/': typeof LibraryAlbumArtistsIndexRoute
  '/library/albums/': typeof LibraryAlbumsIndexRoute
  '/library/albums/$albumArtist/$albumTitle': typeof LibraryAlbumsAlbumArtistAlbumTitleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/settings'
    | '/library/tracks'
    | '/library/'
    | '/library/album-artists/$artistName'
    | '/library/album-artists/'
    | '/library/albums/'
    | '/library/albums/$albumArtist/$albumTitle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/library/tracks'
    | '/library'
    | '/library/album-artists/$artistName'
    | '/library/album-artists'
    | '/library/albums'
    | '/library/albums/$albumArtist/$albumTitle'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/settings'
    | '/library/tracks'
    | '/library/'
    | '/library/album-artists/$artistName'
    | '/library/album-artists/'
    | '/library/albums/'
    | '/library/albums/$albumArtist/$albumTitle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/tracks': {
      id: '/library/tracks'
      path: '/tracks'
      fullPath: '/library/tracks'
      preLoaderRoute: typeof LibraryTracksRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/album-artists/': {
      id: '/library/album-artists/'
      path: '/album-artists'
      fullPath: '/library/album-artists/'
      preLoaderRoute: typeof LibraryAlbumArtistsIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/album-artists/$artistName': {
      id: '/library/album-artists/$artistName'
      path: '/album-artists/$artistName'
      fullPath: '/library/album-artists/$artistName'
      preLoaderRoute: typeof LibraryAlbumArtistsArtistNameRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/albums/': {
      id: '/library/albums/'
      path: '/albums'
      fullPath: '/library/albums/'
      preLoaderRoute: typeof LibraryAlbumsIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/albums/$albumArtist/$albumTitle': {
      id: '/library/albums/$albumArtist/$albumTitle'
      path: '/albums/$albumArtist/$albumTitle'
      fullPath: '/library/albums/$albumArtist/$albumTitle'
      preLoaderRoute: typeof LibraryAlbumsAlbumArtistAlbumTitleRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryTracksRoute: typeof LibraryTracksRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibraryAlbumArtistsArtistNameRoute: typeof LibraryAlbumArtistsArtistNameRoute
  LibraryAlbumArtistsIndexRoute: typeof LibraryAlbumArtistsIndexRoute
  LibraryAlbumsIndexRoute: typeof LibraryAlbumsIndexRoute
  LibraryAlbumsAlbumArtistAlbumTitleRoute: typeof LibraryAlbumsAlbumArtistAlbumTitleRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryTracksRoute: LibraryTracksRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LibraryAlbumArtistsArtistNameRoute: LibraryAlbumArtistsArtistNameRoute,
  LibraryAlbumArtistsIndexRoute: LibraryAlbumArtistsIndexRoute,
  LibraryAlbumsIndexRoute: LibraryAlbumsIndexRoute,
  LibraryAlbumsAlbumArtistAlbumTitleRoute:
    LibraryAlbumsAlbumArtistAlbumTitleRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
