/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeBackend {
  static open(dataDir: string): Promise<NativeBackend>
  getPlaybackState(): Promise<PlaybackSnapshot>
  getPlaybackQueue(): Promise<PlaybackQueueSnapshot>
  pausePlayback(): Promise<PlaybackSnapshot>
  resumePlayback(): Promise<PlaybackSnapshot>
  previousPlayback(): Promise<PlaybackSnapshot>
  nextPlayback(): Promise<PlaybackSnapshot>
  seekPlayback(positionMs: number): Promise<PlaybackSnapshot>
  setPlaybackVolume(volume: number): Promise<PlaybackSnapshot>
  setPlaybackMuted(muted: boolean): Promise<PlaybackSnapshot>
  listAudioOutputDevices(): Promise<Array<AudioOutputDevice>>
  getLibraryStatus(): Promise<LibraryStatus>
  getLibraryTrackForPath(path: string): Promise<LibraryTrackSummary | null>
  listLibraryRoots(): Promise<Array<LibraryRoot>>
  registerLibraryRoot(path: string): Promise<LibraryRoot>
  setLibraryRootEnabled(id: string, enabled: boolean): Promise<LibraryRoot>
  removeLibraryRoot(id: string): Promise<void>
  getLibraryScanState(): Promise<LibraryScanSnapshot>
  startLibraryScan(): Promise<void>
  cancelLibraryScan(): Promise<void>
  listLibraryTracks(cursor: string | null, search: string | null, sortKey: LibraryTrackSortKey, sortDirection: LibrarySortDirection): Promise<LibraryTrackPage>
  listLibraryAlbums(cursor: string | null, search: string | null, sortKey: LibraryAlbumSortKey, sortDirection: LibrarySortDirection): Promise<LibraryAlbumPage>
  listLibraryAlbumArtists(cursor: string | null, search: string | null, sortKey: LibraryAlbumArtistSortKey, sortDirection: LibrarySortDirection): Promise<LibraryAlbumArtistPage>
  getLibraryAlbumArtist(artistKey: LibraryAlbumArtistKey): Promise<LibraryAlbumArtistSummary>
  listLibraryArtistAlbums(artistKey: LibraryAlbumArtistKey, cursor: string | null, sortKey: LibraryArtistAlbumSortKey, sortDirection: LibrarySortDirection): Promise<LibraryAlbumPage>
  getLibraryAlbumDetails(albumKey: LibraryAlbumKey): Promise<LibraryAlbumDetails>
  listLibraryAlbumTracks(albumKey: LibraryAlbumKey, cursor?: string | null): Promise<LibraryAlbumTrackPage>
  startLibraryTrack(trackId: string): Promise<PlaybackSnapshot>
  startLibraryAlbum(albumKey: LibraryAlbumKey): Promise<PlaybackSnapshot>
  nextEvent(): Promise<BackendEvent>
  shutdown(): Promise<void>
}

export interface ApplicationActivity {
  id: string
  kind: ApplicationActivityKind
  state: ApplicationActivityState
}

export type ApplicationActivityKind =  'librarySync';

export type ApplicationActivityState =  'running'|
'attentionRequired';

export type ArtworkMimeType =  'jpeg'|
'png';

export interface ArtworkRef {
  contentHash: string
  mimeType: ArtworkMimeType
  relativePath: string
}

export interface AudioOutputDevice {
  id: string
  name: string
  isDefault: boolean
}

export interface AudioOutputDeviceIdentity {
  id: string
  name: string
}

export type AudioOutputSelection =
  | { kind: 'systemDefault' }
  | { kind: 'device'; deviceId: string }

export type BackendEvent =
  | { event: 'playbackStateChanged'; payload: PlaybackSnapshot }
  | { event: 'playbackQueueStateChanged'; payload: PlaybackQueueSnapshot }
  | { event: 'applicationActivitiesChanged'; payload: Array<ApplicationActivity> }
  | { event: 'libraryScanStateChanged'; payload: LibraryScanSnapshot }

export interface LibraryAlbumArtistKey {
  name: string
}

export interface LibraryAlbumArtistPage {
  items: Array<LibraryAlbumArtistSummary>
  totalCount: number | null | null
  nextCursor: string | null | null
}

export type LibraryAlbumArtistSortKey =  'artist'|
'albumCount'|
'trackCount';

export interface LibraryAlbumArtistSummary {
  key: LibraryAlbumArtistKey
  artwork: ArtworkRef | null | null
  albumCount: number | null | null
  trackCount: number | null | null
}

export interface LibraryAlbumDetails {
  summary: LibraryAlbumSummary
  date: string | null | null
  trackCount: number | null | null
  durationMs: number | null | null
  firstPlayableTrackId: string | null | null
}

export interface LibraryAlbumKey {
  title: string
  albumArtist: string
}

export interface LibraryAlbumPage {
  items: Array<LibraryAlbumSummary>
  totalCount: number | null | null
  nextCursor: string | null | null
}

export type LibraryAlbumSortKey =  'title'|
'artist'|
'year';

export interface LibraryAlbumSummary {
  key: LibraryAlbumKey
  artwork: ArtworkRef | null | null
  year: number | null | null
}

export interface LibraryAlbumTrackPage {
  items: Array<LibraryAlbumTrackSummary>
  totalCount: number
  nextCursor: string | null | null
}

export interface LibraryAlbumTrackSummary {
  id: string
  title: string
  artist: string | null | null
  trackNumber: number | null | null
  discNumber: number | null | null
  fileFormat: string | null | null
  bitDepth: number | null | null
  sampleRate: number | null | null
  durationMs: number | null | null
  availability: LibraryFileAvailability
  playable: boolean
}

export type LibraryArtistAlbumSortKey =  'year'|
'title';

export type LibraryFileAvailability =  'available'|
'missing';

export interface LibraryRoot {
  id: string
  path: string
  enabled: boolean
  scanGeneration: number | null | null
  lastSuccessfulScanAtMs: number | null | null
}

export interface LibraryScanSnapshot {
  state: LibraryScanState
  currentRoot: LibraryRoot | null | null
  discoveredCount: number | null | null
  inspectedCount: number | null | null
  indexedCount: number | null | null
  failedCount: number | null | null
  failureCode: string | null | null
}

export type LibraryScanState =  'idle'|
'running'|
'completed'|
'cancelled'|
'failed';

export type LibrarySortDirection =  'ascending'|
'descending';

export type LibraryStatus =
  | { status: 'ready' }
  | { status: 'unavailable'; reason: LibraryUnavailableReason }

export interface LibraryTrackPage {
  items: Array<LibraryTrackSummary>
  totalCount: number | null | null
  nextCursor: string | null | null
}

export type LibraryTrackSortKey =  'title'|
'artist'|
'album'|
'duration';

export interface LibraryTrackSummary {
  id: string
  title: string
  artist: string | null | null
  album: string | null | null
  albumArtist: string | null | null
  artwork: ArtworkRef | null | null
  durationMs: number | null | null
  availability: LibraryFileAvailability
  playable: boolean
}

export type LibraryUnavailableReason =  'storageUnavailable'|
'databaseOpenFailed'|
'migrationFailed'|
'schemaTooNew'|
'databaseCorrupt';

export type PlaybackChannelConversion =  'none'|
'monoToStereo'|
'stereoToMono';

export type PlaybackFailureCode =  'noOutputDevice'|
'outputDeviceUnavailable'|
'unsupportedOutputConfiguration'|
'outputStreamBuildFailed'|
'outputStreamStartFailed'|
'outputStreamPauseFailed'|
'outputStreamResumeFailed'|
'outputStreamRuntimeFailed'|
'completionTimingFailed'|
'decodeFailed'|
'sampleRateConversionFailed';

export interface PlaybackQueueItem {
  id: string
  title: string
  artist: string | null | null
  durationMs: number | null | null
}

export interface PlaybackQueueSnapshot {
  revision: number | null | null
  current: PlaybackQueueItem | null | null
  upcoming: Array<PlaybackQueueItem>
  repeatMode: PlaybackRepeatMode
  shuffleEnabled: boolean
}

export type PlaybackRepeatMode =  'off'|
'all'|
'one';

export type PlaybackSnapshot =
  | { status: 'stopped'; revision: number; file: ValidatedAudioFile | null | null; volume: number; muted: boolean; outputSelection: AudioOutputSelection; canGoPrevious: boolean; canGoNext: boolean }
  | { status: 'playing'; revision: number; file: ValidatedAudioFile; playbackId: string; positionMs: number; durationMs: number | null | null; volume: number; muted: boolean; outputSelection: AudioOutputSelection; outputDevice: AudioOutputDeviceIdentity; channelConversion: PlaybackChannelConversion; sourceSampleRate: number; outputSampleRate: number; resamplingActive: boolean; canGoPrevious: boolean; canGoNext: boolean }
  | { status: 'paused'; revision: number; file: ValidatedAudioFile; playbackId: string; positionMs: number; durationMs: number | null | null; volume: number; muted: boolean; outputSelection: AudioOutputSelection; outputDevice: AudioOutputDeviceIdentity; channelConversion: PlaybackChannelConversion; sourceSampleRate: number; outputSampleRate: number; resamplingActive: boolean; canGoPrevious: boolean; canGoNext: boolean }
  | { status: 'failed'; revision: number; file: ValidatedAudioFile | null | null; playbackId: string | null | null; error: PlaybackFailureCode; volume: number; muted: boolean; outputSelection: AudioOutputSelection; canGoPrevious: boolean; canGoNext: boolean }

export interface ValidatedAudioFile {
  path: string
  fileName: string
  extension: string
}
