/* eslint-disable */

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  validateAudioFile: (path: string) =>
    __TAURI_INVOKE<ValidatedAudioFile>("validate_audio_file", { path }),
  inspectAudioFile: (path: string) => __TAURI_INVOKE<AudioFileInfo>("inspect_audio_file", { path }),
  listAudioOutputDevices: () => __TAURI_INVOKE<AudioOutputDevice[]>("list_audio_output_devices"),
  startAudioFile: (path: string) =>
    __TAURI_INVOKE<PlaybackSnapshot_Serialize>("start_audio_file", { path }),
  stopAudioPlayback: () => __TAURI_INVOKE<PlaybackSnapshot_Serialize>("stop_audio_playback"),
  pauseAudioPlayback: () => __TAURI_INVOKE<PlaybackSnapshot_Serialize>("pause_audio_playback"),
  resumeAudioPlayback: () => __TAURI_INVOKE<PlaybackSnapshot_Serialize>("resume_audio_playback"),
  seekAudioPlayback: (positionMs: number) =>
    __TAURI_INVOKE<PlaybackSnapshot_Serialize>("seek_audio_playback", { positionMs }),
  getPlaybackState: () => __TAURI_INVOKE<PlaybackSnapshot_Serialize>("get_playback_state"),
};

/* Types */
export type AudioCodec =
  "aac" | "adpcm" | "alac" | "flac" | "mp1" | "mp2" | "mp3" | "pcm" | "vorbis" | "other";

export type AudioDeviceListError = { code: "enumerationFailed" };

export type AudioFileInfo = {
  codec: AudioCodec;
  sampleRate: number;
  channelCount: number;
  durationMs: number | null;
};

export type AudioFileInspectionError =
  | { code: "validationFailed"; error: AudioFileValidationError }
  | { code: "fileOpenFailed" }
  | { code: "unsupportedFormat" }
  | { code: "missingAudioTrack" }
  | { code: "missingCodecParameters" }
  | { code: "unsupportedCodec" }
  | { code: "missingSampleRate" }
  | { code: "missingChannelCount" }
  | { code: "invalidChannelCount" }
  | { code: "corruptedFile" };

export type AudioFileValidationError =
  | { code: "emptyPath" }
  | { code: "notFound" }
  | { code: "notAFile" }
  | {
      code: "unsupportedExtension";
      details: {
        extension: string | null;
      };
    }
  | { code: "invalidFileName" };

export type AudioOutputDevice = {
  id: string;
  name: string;
  isDefault: boolean;
};

export type PauseAudioPlaybackError =
  | { code: "playbackWorkerUnavailable" }
  | { code: "invalidPlaybackState" }
  | { code: "outputFailed" }
  | { code: "taskFailed" };

export type PlaybackFailureCode =
  | "noOutputDevice"
  | "unsupportedOutputConfiguration"
  | "outputStreamBuildFailed"
  | "outputStreamStartFailed"
  | "outputStreamPauseFailed"
  | "outputStreamResumeFailed"
  | "outputStreamRuntimeFailed"
  | "completionTimingFailed"
  | "decodeFailed";

export type PlaybackSnapshot = PlaybackSnapshot_Serialize | PlaybackSnapshot_Deserialize;

export type PlaybackSnapshot_Deserialize =
  | ({ status: "stopped" } & {
      durationMs?: never;
      error?: never;
      playbackId?: never;
      positionMs?: never;
    })
  | ({ status: "playing"; playbackId: string; positionMs: number; durationMs: number | null } & {
      error?: never;
    })
  | ({ status: "paused"; playbackId: string; positionMs: number; durationMs: number | null } & {
      error?: never;
    })
  | ({ status: "failed"; playbackId: string | null; error: PlaybackFailureCode } & {
      durationMs?: never;
      positionMs?: never;
    });

export type PlaybackSnapshot_Serialize =
  | ({ status: "stopped" } & {
      durationMs?: never;
      error?: never;
      playbackId?: never;
      positionMs?: never;
    })
  | ({ status: "playing"; playbackId: string; positionMs: number; durationMs: number | null } & {
      error?: never;
    })
  | ({ status: "paused"; playbackId: string; positionMs: number; durationMs: number | null } & {
      error?: never;
    })
  | ({ status: "failed"; playbackId?: string | null; error: PlaybackFailureCode } & {
      durationMs?: never;
      positionMs?: never;
    });

export type ResumeAudioPlaybackError =
  | { code: "playbackWorkerUnavailable" }
  | { code: "invalidPlaybackState" }
  | { code: "outputFailed" }
  | { code: "taskFailed" };

export type SeekAudioPlaybackError =
  | { code: "invalidPlaybackState" }
  | { code: "durationUnavailable" }
  | { code: "seekFailed" }
  | { code: "decodeFailed" }
  | { code: "outputFailed" }
  | { code: "playbackWorkerUnavailable" }
  | { code: "taskFailed" };

export type StartAudioFileError =
  | { code: "validationFailed"; error: AudioFileValidationError }
  | { code: "decodeFailed" }
  | { code: "outputFailed" }
  | { code: "playbackWorkerUnavailable" }
  | { code: "taskFailed" };

export type StopAudioPlaybackError = { code: "playbackWorkerUnavailable" } | { code: "taskFailed" };

export type ValidatedAudioFile = {
  path: string;
  fileName: string;
  extension: string;
};
