/* eslint-disable */

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  validateAudioFile: (path: string) =>
    __TAURI_INVOKE<ValidatedAudioFile>("validate_audio_file", { path }),
  inspectAudioFile: (path: string) => __TAURI_INVOKE<AudioFileInfo>("inspect_audio_file", { path }),
  listAudioOutputDevices: () => __TAURI_INVOKE<AudioOutputDevice[]>("list_audio_output_devices"),
  startAudioFile: (path: string) =>
    __TAURI_INVOKE<PlaybackSnapshot_Serialize>("start_audio_file", { path }),
  stopAudioPlayback: () => __TAURI_INVOKE<PlaybackSnapshot_Serialize>("stop_audio_playback"),
  pauseAudioPlayback: () => __TAURI_INVOKE<PlaybackSnapshot_Serialize>("pause_audio_playback"),
  resumeAudioPlayback: () => __TAURI_INVOKE<PlaybackSnapshot_Serialize>("resume_audio_playback"),
  seekAudioPlayback: (positionMs: number) =>
    __TAURI_INVOKE<PlaybackSnapshot_Serialize>("seek_audio_playback", { positionMs }),
  setAudioOutputSelection: (selection: AudioOutputSelection) =>
    __TAURI_INVOKE<PlaybackSnapshot_Serialize>("set_audio_output_selection", { selection }),
  setPlaybackVolume: (volume: number) =>
    __TAURI_INVOKE<PlaybackSnapshot_Serialize>("set_playback_volume", { volume }),
  muteAudioPlayback: () => __TAURI_INVOKE<PlaybackSnapshot_Serialize>("mute_audio_playback"),
  unmuteAudioPlayback: () => __TAURI_INVOKE<PlaybackSnapshot_Serialize>("unmute_audio_playback"),
  getPlaybackState: () => __TAURI_INVOKE<PlaybackSnapshot_Serialize>("get_playback_state"),
  getLibraryStatus: () => __TAURI_INVOKE<LibraryStatus>("get_library_status"),
  listLibraryRoots: () => __TAURI_INVOKE<LibraryRoot[]>("list_library_roots"),
  registerLibraryRoot: (path: string) =>
    __TAURI_INVOKE<LibraryRoot>("register_library_root", { path }),
  setLibraryRootEnabled: (id: string, enabled: boolean) =>
    __TAURI_INVOKE<LibraryRoot>("set_library_root_enabled", { id, enabled }),
  startLibraryScan: () => __TAURI_INVOKE<null>("start_library_scan"),
  cancelLibraryScan: () => __TAURI_INVOKE<null>("cancel_library_scan"),
  getLibraryScanState: () => __TAURI_INVOKE<LibraryScanSnapshot>("get_library_scan_state"),
  listLibraryTracks: (afterId: string | null, search: string | null) =>
    __TAURI_INVOKE<LibraryTrackPage>("list_library_tracks", { afterId, search }),
  listLibraryAlbums: (afterId: string | null, search: string | null) =>
    __TAURI_INVOKE<LibraryAlbumPage>("list_library_albums", { afterId, search }),
  removeLibraryRoot: (id: string) => __TAURI_INVOKE<null>("remove_library_root", { id }),
  getLibraryTrackForPath: (path: string) =>
    __TAURI_INVOKE<{
      id: string;
      title: string;
      artist: string | null;
      album: string | null;
      albumArtist: string | null;
      artwork: ArtworkRef | null;
      durationMs: number | null;
      availability: LibraryFileAvailability;
      playable: boolean;
    } | null>("get_library_track_for_path", { path }),
  startLibraryTrack: (trackId: string) =>
    __TAURI_INVOKE<PlaybackSnapshot_Serialize>("start_library_track", { trackId }),
};

/* Types */
export type ArtworkMimeType = "jpeg" | "png";

export type ArtworkRef = {
  contentHash: string;
  mimeType: ArtworkMimeType;
  relativePath: string;
};

export type AudioCodec =
  "aac" | "adpcm" | "alac" | "flac" | "mp1" | "mp2" | "mp3" | "pcm" | "vorbis" | "other";

export type AudioDeviceListError = { code: "enumerationFailed" };

export type AudioFileInfo = {
  codec: AudioCodec;
  sampleRate: number;
  channelCount: number;
  durationMs: number | null;
};

export type AudioFileInspectionError =
  | { code: "validationFailed"; error: AudioFileValidationError }
  | { code: "fileOpenFailed" }
  | { code: "unsupportedFormat" }
  | { code: "missingAudioTrack" }
  | { code: "missingCodecParameters" }
  | { code: "unsupportedCodec" }
  | { code: "missingSampleRate" }
  | { code: "missingChannelCount" }
  | { code: "invalidChannelCount" }
  | { code: "corruptedFile" };

export type AudioFileValidationError =
  | { code: "emptyPath" }
  | { code: "notFound" }
  | { code: "notAFile" }
  | {
      code: "unsupportedExtension";
      details: {
        extension: string | null;
      };
    }
  | { code: "invalidFileName" };

export type AudioOutputDevice = {
  id: string;
  name: string;
  isDefault: boolean;
};

export type AudioOutputDeviceIdentity = {
  id: string;
  name: string;
};

export type AudioOutputSelection = { kind: "systemDefault" } | { kind: "device"; deviceId: string };

export type LibraryAlbumPage = {
  items: LibraryAlbumSummary[];
  nextAfterId: string | null;
};

export type LibraryAlbumSummary = {
  id: string;
  title: string;
  albumArtist: string;
  artwork: ArtworkRef | null;
};

export type LibraryCommandError =
  | { code: "invalidRoot" }
  | { code: "rootNotFound" }
  | { code: "rootNotDirectory" }
  | { code: "canonicalizationFailed" }
  | { code: "duplicateRoot" }
  | { code: "overlappingRoot" }
  | { code: "scanInProgress" }
  | { code: "invalidId" }
  | { code: "rootMissing" }
  | { code: "scanAlreadyRunning" }
  | { code: "noEnabledRoots" }
  | { code: "scanNotRunning" }
  | { code: "libraryUnavailable" }
  | { code: "persistenceFailed" }
  | { code: "taskFailed" };

export type LibraryFileAvailability = "available" | "missing";

export type LibraryRoot = {
  id: string;
  path: string;
  enabled: boolean;
  scanGeneration: number;
  lastSuccessfulScanAtMs: number | null;
};

export type LibraryScanSnapshot = {
  state: LibraryScanState;
  currentRoot: LibraryRoot | null;
  discoveredCount: number;
  inspectedCount: number;
  indexedCount: number;
  failedCount: number;
  failureCode: string | null;
};

export type LibraryScanState = "idle" | "running" | "completed" | "cancelled" | "failed";

export type LibraryStatus =
  { status: "ready" } | { status: "unavailable"; reason: LibraryUnavailableReason };

export type LibraryTrackPage = {
  items: LibraryTrackSummary[];
  nextAfterId: string | null;
};

export type LibraryTrackSummary = {
  id: string;
  title: string;
  artist: string | null;
  album: string | null;
  albumArtist: string | null;
  artwork: ArtworkRef | null;
  durationMs: number | null;
  availability: LibraryFileAvailability;
  playable: boolean;
};

export type LibraryUnavailableReason =
  | "storageUnavailable"
  | "databaseOpenFailed"
  | "migrationFailed"
  | "schemaTooNew"
  | "databaseCorrupt";

export type PauseAudioPlaybackError =
  | { code: "playbackWorkerUnavailable" }
  | { code: "invalidPlaybackState" }
  | { code: "outputFailed" }
  | { code: "taskFailed" };

export type PlaybackChannelConversion = "none" | "monoToStereo" | "stereoToMono";

export type PlaybackFailureCode =
  | "noOutputDevice"
  | "outputDeviceUnavailable"
  | "unsupportedOutputConfiguration"
  | "outputStreamBuildFailed"
  | "outputStreamStartFailed"
  | "outputStreamPauseFailed"
  | "outputStreamResumeFailed"
  | "outputStreamRuntimeFailed"
  | "completionTimingFailed"
  | "decodeFailed"
  | "sampleRateConversionFailed";

export type PlaybackMuteError = { code: "playbackWorkerUnavailable" } | { code: "taskFailed" };

export type PlaybackSnapshot = PlaybackSnapshot_Serialize | PlaybackSnapshot_Deserialize;

export type PlaybackSnapshot_Deserialize =
  | ({
      status: "stopped";
      revision: number;
      file: ValidatedAudioFile | null;
      volume: number;
      muted: boolean;
      outputSelection: AudioOutputSelection;
    } & {
      channelConversion?: never;
      durationMs?: never;
      error?: never;
      outputDevice?: never;
      outputSampleRate?: never;
      playbackId?: never;
      positionMs?: never;
      resamplingActive?: never;
      sourceSampleRate?: never;
    })
  | ({
      status: "playing";
      revision: number;
      file: ValidatedAudioFile;
      playbackId: string;
      positionMs: number;
      durationMs: number | null;
      volume: number;
      muted: boolean;
      outputSelection: AudioOutputSelection;
      outputDevice: AudioOutputDeviceIdentity;
      channelConversion: PlaybackChannelConversion;
      sourceSampleRate: number;
      outputSampleRate: number;
      resamplingActive: boolean;
    } & { error?: never })
  | ({
      status: "paused";
      revision: number;
      file: ValidatedAudioFile;
      playbackId: string;
      positionMs: number;
      durationMs: number | null;
      volume: number;
      muted: boolean;
      outputSelection: AudioOutputSelection;
      outputDevice: AudioOutputDeviceIdentity;
      channelConversion: PlaybackChannelConversion;
      sourceSampleRate: number;
      outputSampleRate: number;
      resamplingActive: boolean;
    } & { error?: never })
  | ({
      status: "failed";
      revision: number;
      file: ValidatedAudioFile | null;
      playbackId: string | null;
      error: PlaybackFailureCode;
      volume: number;
      muted: boolean;
      outputSelection: AudioOutputSelection;
    } & {
      channelConversion?: never;
      durationMs?: never;
      outputDevice?: never;
      outputSampleRate?: never;
      positionMs?: never;
      resamplingActive?: never;
      sourceSampleRate?: never;
    });

export type PlaybackSnapshot_Serialize =
  | ({
      status: "stopped";
      revision: number;
      file: ValidatedAudioFile | null;
      volume: number;
      muted: boolean;
      outputSelection: AudioOutputSelection;
    } & {
      channelConversion?: never;
      durationMs?: never;
      error?: never;
      outputDevice?: never;
      outputSampleRate?: never;
      playbackId?: never;
      positionMs?: never;
      resamplingActive?: never;
      sourceSampleRate?: never;
    })
  | ({
      status: "playing";
      revision: number;
      file: ValidatedAudioFile;
      playbackId: string;
      positionMs: number;
      durationMs: number | null;
      volume: number;
      muted: boolean;
      outputSelection: AudioOutputSelection;
      outputDevice: AudioOutputDeviceIdentity;
      channelConversion: PlaybackChannelConversion;
      sourceSampleRate: number;
      outputSampleRate: number;
      resamplingActive: boolean;
    } & { error?: never })
  | ({
      status: "paused";
      revision: number;
      file: ValidatedAudioFile;
      playbackId: string;
      positionMs: number;
      durationMs: number | null;
      volume: number;
      muted: boolean;
      outputSelection: AudioOutputSelection;
      outputDevice: AudioOutputDeviceIdentity;
      channelConversion: PlaybackChannelConversion;
      sourceSampleRate: number;
      outputSampleRate: number;
      resamplingActive: boolean;
    } & { error?: never })
  | ({
      status: "failed";
      revision: number;
      file: ValidatedAudioFile | null;
      playbackId?: string | null;
      error: PlaybackFailureCode;
      volume: number;
      muted: boolean;
      outputSelection: AudioOutputSelection;
    } & {
      channelConversion?: never;
      durationMs?: never;
      outputDevice?: never;
      outputSampleRate?: never;
      positionMs?: never;
      resamplingActive?: never;
      sourceSampleRate?: never;
    });

export type ResumeAudioPlaybackError =
  | { code: "playbackWorkerUnavailable" }
  | { code: "invalidPlaybackState" }
  | { code: "outputFailed" }
  | { code: "taskFailed" };

export type SeekAudioPlaybackError =
  | { code: "invalidPlaybackState" }
  | { code: "durationUnavailable" }
  | { code: "seekFailed" }
  | { code: "decodeFailed" }
  | { code: "outputFailed" }
  | { code: "playbackWorkerUnavailable" }
  | { code: "taskFailed" };

export type SetAudioOutputSelectionError =
  | { code: "invalidDeviceId" }
  | { code: "outputDeviceUnavailable" }
  | { code: "invalidPlaybackState" }
  | { code: "playbackWorkerUnavailable" }
  | { code: "taskFailed" };

export type SetPlaybackVolumeError =
  { code: "invalidVolume" } | { code: "playbackWorkerUnavailable" } | { code: "taskFailed" };

export type StartAudioFileError =
  | { code: "validationFailed"; error: AudioFileValidationError }
  | { code: "decodeFailed" }
  | { code: "noOutputDevice" }
  | { code: "outputDeviceUnavailable" }
  | { code: "outputFailed" }
  | { code: "playbackWorkerUnavailable" }
  | { code: "taskFailed" };

export type StartLibraryTrackError =
  | { code: "invalidId" }
  | { code: "trackNotFound" }
  | { code: "trackUnavailable" }
  | { code: "trackNotPlayable" }
  | { code: "libraryUnavailable" }
  | { code: "persistenceFailed" }
  | { code: "decodeFailed" }
  | { code: "noOutputDevice" }
  | { code: "outputDeviceUnavailable" }
  | { code: "outputFailed" }
  | { code: "playbackWorkerUnavailable" }
  | { code: "taskFailed" };

export type StopAudioPlaybackError = { code: "playbackWorkerUnavailable" } | { code: "taskFailed" };

export type ValidatedAudioFile = {
  path: string;
  fileName: string;
  extension: string;
};
